//! The trait that every `#[wave_db]`-annotated struct implements.

use crate::Shape;

/// Trait implemented by the `#[wave_db]` proc-macro on every annotated struct.
///
/// Provides compile-time constants for struct identification and classification.
pub trait WaveDbStruct {
    /// The permanent struct family identifier (u20, shared across versions).
    const STRUCT_ID: u32;
    /// The schema version, parsed from the trailing integer of the type name.
    const STRUCT_VERSION: u8;
    /// The data shape: `Unique`, `NonUnique`, or `NestedNonUnique`.
    const SHAPE: Shape;
}

/// Compile-time chain link **backward**: `Self` migrates *from* `Source` (older).
///
/// Implementing this on `Message2` with `Source = Message1` expresses that
/// `Message2` is the direct successor of `Message1` in the schema evolution
/// chain.  The full chain is traversable at compile time by following
/// `<T as MigratesFrom>::Source` recursively:
///
/// ```text
/// Message3::Source          → Message2
/// Message3::Source::Source  → Message1   (first version, no MigratesFrom)
/// ```
///
/// Generated by `#[wave_db(migrate_from = TypeName, …)]`.
pub trait MigratesFrom: WaveDbStruct {
    /// The struct version that immediately precedes `Self` in the chain.
    type Source: WaveDbStruct;
}

/// Compile-time chain link **forward**: `Self` accepts a rollback *from* `Future` (newer).
///
/// Implementing this on `Message1` with `Future = Message2` expresses that
/// `Message1` knows how to receive a rolled-back `Message2` and produce
/// `Message1`.  Co-locating the rollback target with the older struct keeps
/// the inverse operation next to the type it produces.
///
/// The full forward chain is traversable at compile time:
///
/// ```text
/// Message1::Future          → Message2
/// Message1::Future::Future  → Message3   (current head, no RollbackFrom)
/// ```
///
/// Generated by `#[wave_db(migrate_rollback = TypeName, …)]`.
pub trait RollbackFrom: WaveDbStruct {
    /// The struct version that immediately follows `Self` in the chain.
    type Future: WaveDbStruct;
}

/// Walk the migration chain at read time to deserialize raw bytes as `Self`.
///
/// Every `#[wave_db]`-annotated struct gets a generated impl that:
///
/// - **If `stored_version == Self::STRUCT_VERSION`** → postcard-deserialize directly.
/// - **If `stored_version < Self::STRUCT_VERSION`** → recursively read as
///   `<Self as MigratesFrom>::Source`, then call `Self::__wave_db_migrate_from`
///   to upgrade to `Self`.  Chain end (no `migrate_from` declared) is an error.
/// - **If `stored_version > Self::STRUCT_VERSION`** → recursively read as
///   `<Self as RollbackFrom>::Future`, then call `Self::__wave_db_migrate_rollback`
///   to downgrade to `Self`.  Chain end (no `migrate_rollback` declared) is an error.
///
/// The trait is generic over the `Db` handle type so it works with any
/// transport (concrete `wavedb::Db`, mocks, future variants).  The user's
/// migration fns must be generic over `Db` so the bound resolves at the call
/// site.
///
/// This is how `Message41::search(&db)` returns a `Message41` even when the
/// stored bytes are version 42, and how `Message42::search(&db)` upgrades an
/// older v41 record on first read — **no special registry call required**;
/// the chain comes entirely from the type system via `MigratesFrom` /
/// `RollbackFrom`.
pub trait MigrationChain<Db>:
    WaveDbStruct + Sized + Send + for<'de> serde::Deserialize<'de>
where
    Db: Send + Sync,
{
    /// Read raw postcard bytes at `stored_version` and produce `Self`.
    ///
    /// Returns a boxed future to allow mutual recursion across the chain.
    fn read_as_self<'a>(
        db: &'a Db,
        bytes: &'a [u8],
        stored_version: u8,
    ) -> ::core::pin::Pin<
        ::std::boxed::Box<
            dyn ::core::future::Future<Output = crate::Result<Self>>
                + Send
                + 'a,
        >,
    >
    where
        Db: 'a;
}
