[package]
name = "wavedb-quick-node"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "wavedb-quick-node"
path = "src/main.rs"

[dependencies]
wavedb-core = { path = "../wavedb-core" }
wavedb-storage = { path = "../wavedb-storage" }
wavedb-net = { path = "../wavedb-net" }
tokio.workspace = true
